In [1]:
import pandas as pd
import numpy as np

In [2]:
cars=pd.read_csv('cars.csv')
cars.head()

,Unnamed: 0,name,mileage,year,gearbox,transmission,horsepower,fuel,price
0,0,Ford Ecosport Trend,131 000 km,2016,Automatique,Traction,6 cv,Essence,55000.0
1,1,Peugeot Partner,60 000 km,2011,Manuelle,Traction,6 cv,Diesel,23000.0
2,2,Hyundai i30 Fastback,65 035 km,2023,Automatique,Traction,7 cv,Essence,75000.0
3,3,Mercedes-Benz Classe C AMG +,87 000 km,2017,Automatique,Propulsion,8 cv,Essence,95000.0
4,4,Geely GX3,41 000 km,2021,Manuelle,Traction,6 cv,Essence,51000.0

In [3]:
cars.shape

(1800, 9)

In [4]:
cars=cars.drop(columns=['Unnamed: 0'])

In [5]:
cars.head()

,name,mileage,year,gearbox,transmission,horsepower,fuel,price
0,Ford Ecosport Trend,131 000 km,2016,Automatique,Traction,6 cv,Essence,55000.0
1,Peugeot Partner,60 000 km,2011,Manuelle,Traction,6 cv,Diesel,23000.0
2,Hyundai i30 Fastback,65 035 km,2023,Automatique,Traction,7 cv,Essence,75000.0
3,Mercedes-Benz Classe C AMG +,87 000 km,2017,Automatique,Propulsion,8 cv,Essence,95000.0
4,Geely GX3,41 000 km,2021,Manuelle,Traction,6 cv,Essence,51000.0

In [6]:
cars['mileage']=cars['mileage'].str.replace(" ","").str.replace("km","").astype(int)

In [7]:
cars.head()

,name,mileage,year,gearbox,transmission,horsepower,fuel,price
0,Ford Ecosport Trend,131000,2016,Automatique,Traction,6 cv,Essence,55000.0
1,Peugeot Partner,60000,2011,Manuelle,Traction,6 cv,Diesel,23000.0
2,Hyundai i30 Fastback,65035,2023,Automatique,Traction,7 cv,Essence,75000.0
3,Mercedes-Benz Classe C AMG +,87000,2017,Automatique,Propulsion,8 cv,Essence,95000.0
4,Geely GX3,41000,2021,Manuelle,Traction,6 cv,Essence,51000.0

In [8]:
wa=cars[cars["price"]<1000]
wa.head()

Empty DataFrame
Columns: [name, mileage, year, gearbox, transmission, horsepower, fuel, price]
Index: []

In [9]:
cars.isnull().sum()

name             0
mileage          0
year             0
gearbox          0
transmission     0
horsepower       0
fuel             0
price           33
dtype: int64

In [10]:
cars=cars.dropna()

In [11]:
cars.shape

(1767, 8)

In [12]:
cars.describe()

             mileage         year          price
count    1767.000000  1767.000000    1767.000000
mean   126872.394454  2017.216186   81751.046972
std     93596.049855     7.869599   61862.972163
min         0.000000  1972.000000    8700.000000
25%     57987.000000  2015.000000   39900.000000
50%    109248.000000  2019.000000   65000.000000
75%    179000.000000  2022.000000  100000.000000
max    800000.000000  2026.000000  440000.000000

In [13]:
print(cars['horsepower'].unique())

['6 cv' '7 cv' '8 cv' '4 cv' '5 cv' '26 cv' '9 cv' '11 cv' '10 cv' '12 cv'
 '19 cv' '22 cv' '13 cv' '15 cv' '43 cv' '29 cv' '33 cv' '21 cv' '18 cv'
 '14 cv' '16 cv' '23 cv' 'plus de 48 cv' '17 cv' '25 cv' '44 cv' '30 cv'
 '28 cv' '3 cv' '24 cv' '20 cv' '37 cv' '34 cv' '27 cv']

In [14]:
cleaned=[]
for row in cars['horsepower']:
    if row=="plus de 48 cv":
        row=row.replace("plus de","")
    row=row.replace("cv","")
    row=row.strip()
    cleaned.append(int(row))
cars['horsepower']=cleaned
cars.head()

,name,mileage,year,gearbox,transmission,horsepower,fuel,price
0,Ford Ecosport Trend,131000,2016,Automatique,Traction,6,Essence,55000.0
1,Peugeot Partner,60000,2011,Manuelle,Traction,6,Diesel,23000.0
2,Hyundai i30 Fastback,65035,2023,Automatique,Traction,7,Essence,75000.0
3,Mercedes-Benz Classe C AMG +,87000,2017,Automatique,Propulsion,8,Essence,95000.0
4,Geely GX3,41000,2021,Manuelle,Traction,6,Essence,51000.0

In [15]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1767 entries, 0 to 1799
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          1767 non-null   object
 1   mileage       1767 non-null   int64
 2   year          1767 non-null   int64
 3   gearbox       1767 non-null   object
 4   transmission  1767 non-null   object
 5   horsepower    1767 non-null   int64
 6   fuel          1767 non-null   object
 7   price         1767 non-null   float64
dtypes: float64(1), int64(3), object(4)
memory usage: 124.2+ KB

In [16]:
print(cars.columns.tolist())
print(cars.shape)
print(cars.dtypes)

['name', 'mileage', 'year', 'gearbox', 'transmission', 'horsepower', 'fuel', 'price']
(1767, 8)
name             object
mileage           int64
year              int64
gearbox          object
transmission     object
horsepower        int64
fuel             object
price           float64
dtype: object

In [17]:
cars['name'].nunique()

729

In [18]:
cars['brand'] = cars['name'].str.split().str[0]   # first word = brand

In [19]:
cars.dtypes

name             object
mileage           int64
year              int64
gearbox          object
transmission     object
horsepower        int64
fuel             object
price           float64
brand            object
dtype: object

In [20]:

cars = pd.get_dummies(cars, columns=['brand'])

In [21]:
cars.dtypes

name                    object
mileage                  int64
year                     int64
gearbox                 object
transmission            object
horsepower               int64
fuel                    object
price                  float64
brand_Alfa                bool
brand_Audi                bool
brand_BMW                 bool
brand_BYD                 bool
brand_Changan             bool
brand_Chery               bool
brand_Chevrolet           bool
brand_Citroën             bool
brand_Cupra               bool
brand_DFSK                bool
brand_DS                  bool
brand_Dacia               bool
brand_Dongfeng            bool
brand_Fiat                bool
brand_Ford                bool
brand_GWM                 bool
brand_Geely               bool
brand_Honda               bool
brand_Hummer              bool
brand_Hyundai             bool
brand_Isuzu               bool
brand_Iveco               bool
brand_Jaguar              bool
brand_Jeep                bool
brand_Jetour              bool
brand_KIA                 bool
brand_Lada                bool
brand_Lancia              bool
brand_Land                bool
brand_MG                  bool
brand_Mahindra            bool
brand_Mazda               bool
brand_Mercedes-Benz       bool
brand_Mini                bool
brand_Mitsubishi          bool
brand_Nissan              bool
brand_Opel                bool
brand_Peugeot             bool
brand_Porsche             bool
brand_Renault             bool
brand_Seat                bool
brand_Skoda               bool
brand_Smart               bool
brand_Soueast             bool
brand_Ssangyong           bool
brand_Suzuki              bool
brand_Tesla               bool
brand_Toyota              bool
brand_Volkswagen          bool
brand_Volvo               bool
brand_Wallyscar           bool
dtype: object

In [22]:
cars=cars.drop(columns=["name"])

In [23]:
cars.to_csv("model_data.csv")